# This is a combination of 2 commits. (#201) (#205)
# This is the 1st commit message:

edit pre-commit file intest/git-hooks to setup stylelint to run on git commit

# The commit message #2 will be skipped:

# edit pre-commit script to remove reference to scss files as they should not be linted

diff --git a/web/profiles/utexas/tests/git-hooks/pre-commit b/web/profiles/utexas/tests/git-hooks/pre-commit
--- a/web/profiles/utexas/tests/git-hooks/pre-commit
+++ b/web/profiles/utexas/tests/git-hooks/pre-commit
@@ -1,4 +1,6 @@
 #!/usr/bin/env bash
+
+# First run PHP Code Sniffer
 source "${BASH_SOURCE[0]%/*}/path-includes"
 PHP_LIST=$( git diff --name-only --cached --diff-filter=ACM -- '*.php' '*.inc' '*.yml' '*.module' '*.install')
 
@@ -14,4 +16,30 @@ fi
 if [ ! -z "$PHP_LIST" ];
   then
     $PHPCS_BIN --standard=$RULESET ${PHP_LIST}
+fi
+
+# If a PHPCS violation has been found, exit without CSS sniffing
+if [[ $? -ne 0 ]] ; then
+    exit 1
+fi
+
+# Stylelinting is run separately.
+STYLELINTER=node_modules/.bin/stylelint
+if [ ! -f $STYLELINTER ];
+  then
+    echo "WARNING: Stylelint was not found. This commit might include coding standards violations. You can fix this by running `npm install` in the repository root."
+    exit 1
+  else
+    echo "Linting staged files via Stylelint."
+    echo "To bypass this check, add '--no-verify' to your commit command"
+fi
+
+CSS_LIST=$( git diff --name-only --cached --diff-filter=ACM -- '*.css')
+if [ ! -z "$CSS_LIST" ];
+  then
+    $STYLELINTER ${CSS_LIST}
+fi
+
+if [[ $? -ne 0 ]] ; then
+    exit 1
 fi
